import ExcelJS from "exceljs";
import type { BulkSearchResult, ComponentSearchHit } from "@sbom/shared";

/**
 * Renders bulk search results as a real `.xlsx` workbook.
 *
 * A genuine spreadsheet rather than a CSV with an `.xls` name — Excel shows a
 * "the file format does not match" warning for those, and the warning teaches
 * people to distrust exports. The format also earns its place here: one file
 * carries three sheets, so the verdict, the matching applications and the
 * unparsed lines travel together, which CSV cannot do.
 *
 * `exceljs` pulls in `uuid@8`, which carries a moderate advisory about a missing
 * buffer bounds check in v3/v5/v6 when the caller supplies a `buf`. Not reachable
 * from here: exceljs imports only `v4` and calls it with no arguments, in one file
 * that generates conditional-formatting ids.
 */

const HEADER_FILL = "FFF3F4F6";
const BORDER: Partial<ExcelJS.Borders> = {
  bottom: { style: "thin", color: { argb: "FFE5E7EB" } },
};

export interface BulkXlsxInput {
  result: BulkSearchResult;
  matches: ComponentSearchHit[];
  matchesTruncated: boolean;
  /** Echoed onto the summary sheet so a circulated file carries its own provenance. */
  generatedAt: Date;
  generatedBy: string | null;
  /** Absolute URL of the saved list, so the file links back to a live view. */
  listUrl: string;
  /**
   * Whether vulnerability scanning is enabled, which decides the note on the summary sheet.
   *
   * A spreadsheet gets forwarded and quoted months later, so its disclaimer has to be true
   * at the moment it was written: "this platform does not match against CVE feeds" is
   * correct with scanning off and a falsehood with it on.
   */
  vulnScanningEnabled: boolean;
}

export async function renderBulkXlsx(input: BulkXlsxInput): Promise<Buffer> {
  const { result, matches, generatedAt } = input;

  const book = new ExcelJS.Workbook();
  book.creator = "SBOM Platform";
  book.created = generatedAt;

  summarySheet(book, input);
  rollupSheet(book, result);
  matchesSheet(book, matches, input.matchesTruncated);
  // Only when there are any: an empty "Not understood" sheet in every export
  // trains people to ignore the one that matters.
  if (result.parse.problems.length > 0) problemsSheet(book, result);

  const buffer = await book.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

/**
 * Provenance and totals.
 *
 * First sheet because a spreadsheet gets forwarded, renamed and quoted weeks
 * later, and an export whose scope and date are unknown is one whose numbers get
 * misattributed. It also records the *scope*, without which "12 applications" is
 * not a claim anyone can check.
 */
function summarySheet(book: ExcelJS.Workbook, input: BulkXlsxInput): void {
  const { result, generatedAt, generatedBy, listUrl } = input;
  const sheet = book.addWorksheet("Summary");
  sheet.columns = [
    { key: "label", width: 32 },
    { key: "value", width: 76 },
  ];

  sheet.addRow(["Package list search"]).font = { bold: true, size: 14 };
  sheet.addRow([]);

  const rows: Array<[string, string | number]> = [
    ["Generated", generatedAt.toISOString().replace("T", " ").slice(0, 16) + " UTC"],
    ["Generated by", generatedBy ?? "—"],
    ["Scope", SCOPE_LABELS[result.scope]],
    ["Shareable link", listUrl],
    ["", ""],
    ["Packages searched", result.parse.entries],
    ["Matched", result.summary.found],
    // "No match", not "not found": a pinned version that misses counts here even
    // though the package itself may be deployed.
    ["No match", result.summary.notFound],
    ["In a current build", result.summary.inCurrentUse],
    ["Applications affected", result.summary.applicationsAffected],
    ["", ""],
    ["Lines submitted", result.parse.lines],
    ["Duplicates collapsed", result.parse.duplicatesCollapsed],
    ["Version specifiers ignored", result.parse.constraintsDropped],
    ["Lines not understood", result.parse.problems.length],
  ];

  for (const [label, value] of rows) {
    const row = sheet.addRow({ label, value });
    row.getCell("label").font = { bold: true, color: { argb: "FF6B7280" } };
  }

  sheet.addRow([]);
  const note = sheet.addRow([
    "Note",
    input.vulnScanningEnabled
      ? "This sheet reports presence, not risk. A package listed here is present in the estate; " +
        "open it in the platform to see whether any advisory affects that version."
      : "This platform does not match packages against CVE feeds. A package listed here is present " +
        "in the estate; that is not a statement about whether it is vulnerable.",
  ]);
  note.getCell(1).font = { bold: true, color: { argb: "FF6B7280" } };
  note.getCell(2).alignment = { wrapText: true };
}

/**
 * One row per submitted package — the sheet the export exists for.
 *
 * Not-found rows are kept and highlighted rather than filtered out. If three of
 * forty packages are present, the other thirty-seven are the answer, and a
 * spreadsheet that dropped them would leave the reader diffing lists by hand.
 */
function rollupSheet(book: ExcelJS.Workbook, result: BulkSearchResult): void {
  const sheet = book.addWorksheet("Packages");
  sheet.columns = [
    { header: "Line", key: "line", width: 7 },
    { header: "Submitted as", key: "raw", width: 34 },
    { header: "Package", key: "name", width: 30 },
    { header: "Version asked for", key: "version", width: 20 },
    { header: "Match", key: "kind", width: 16 },
    { header: "Result", key: "result", width: 14 },
    { header: "Ecosystems", key: "ecosystems", width: 18 },
    { header: "Versions present", key: "versions", width: 40 },
    // Application counts, deliberately not reusing the verdict words.
    { header: "Apps now", key: "current", width: 12 },
    { header: "Apps dropped", key: "historical", width: 14 },
  ];
  styleHeader(sheet);

  for (const row of result.rollup) {
    const verdict = verdictOf(row);
    const added = sheet.addRow({
      line: row.line,
      raw: row.raw,
      name: row.name,
      version: row.version ?? "any",
      kind: VERSION_KIND_LABELS[row.versionKind],
      result: verdict.label,
      ecosystems: row.ecosystems.join(", "),
      versions: row.versionsFound.join(", ") + (row.versionsTruncated ? ", …" : ""),
      current: row.currentApplications,
      historical: row.historicalApplications,
    });

    // Colour carries the verdict at a glance, which is how a 200-row sheet is
    // actually read.
    added.eachCell((cell) => {
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: verdict.fill } };
      cell.border = BORDER;
    });
    added.getCell("result").font = { bold: true, color: { argb: verdict.text } };
  }

  // Freeze the header and turn on filters: a reader's first action on this sheet
  // is almost always "show me only the not-found rows".
  sheet.views = [{ state: "frozen", ySplit: 1 }];
  sheet.autoFilter = { from: "A1", to: { row: 1, column: sheet.columnCount } };
}

/** The flat package × application table: which application, which build, still there or not. */
function matchesSheet(
  book: ExcelJS.Workbook,
  matches: readonly ComponentSearchHit[],
  truncated: boolean,
): void {
  const sheet = book.addWorksheet("Matches");
  sheet.columns = [
    { header: "Package", key: "name", width: 30 },
    { header: "Version", key: "version", width: 22 },
    { header: "Ecosystem", key: "ecosystem", width: 14 },
    { header: "Application", key: "application", width: 30 },
    { header: "App status", key: "status", width: 14 },
    { header: "Usage", key: "usage", width: 12 },
    { header: "Last seen build", key: "build", width: 16 },
    { header: "Last seen", key: "lastSeen", width: 22 },
    { header: "purl", key: "purl", width: 56 },
  ];
  styleHeader(sheet);

  for (const hit of matches) {
    const row = sheet.addRow({
      name: hit.componentName,
      version: hit.componentVersion ?? "—",
      ecosystem: hit.ecosystem,
      application: hit.applicationName,
      status: hit.applicationStatus,
      usage: hit.usage === "current" ? "Current" : "Removed",
      build: hit.lastSeenBuildNumber ?? "—",
      lastSeen: hit.lastSeenAt.replace("T", " ").slice(0, 16),
      purl: hit.purl ?? "",
    });
    row.eachCell((cell) => {
      cell.border = BORDER;
    });
  }

  if (matches.length === 0) {
    sheet.addRow({ name: "No application matched any package on the list." }).font = {
      italic: true,
      color: { argb: "FF6B7280" },
    };
  }
  if (truncated) {
    // Said out loud: a truncated export that looks complete is worse than no
    // export, because it gets treated as the full picture.
    const note = sheet.addRow({
      name: "Truncated — more matches exist than this sheet can hold. Narrow the list or the scope.",
    });
    note.font = { bold: true, color: { argb: "FFB45309" } };
  }

  sheet.views = [{ state: "frozen", ySplit: 1 }];
  sheet.autoFilter = { from: "A1", to: { row: 1, column: sheet.columnCount } };
}

/**
 * Lines the parser could not read.
 *
 * Its own sheet, present only when there are any. These are the lines whose
 * packages were *not searched*, so leaving them out of the file would make the
 * export quietly incomplete.
 */
function problemsSheet(book: ExcelJS.Workbook, result: BulkSearchResult): void {
  const sheet = book.addWorksheet("Not understood");
  sheet.columns = [
    { header: "Line", key: "line", width: 7 },
    { header: "Submitted as", key: "raw", width: 50 },
    { header: "Why it was skipped", key: "reason", width: 50 },
  ];
  styleHeader(sheet);

  for (const problem of result.parse.problems) {
    const row = sheet.addRow({ line: problem.line, raw: problem.raw, reason: problem.reason });
    row.eachCell((cell) => {
      cell.border = BORDER;
    });
  }
  sheet.views = [{ state: "frozen", ySplit: 1 }];
}

function styleHeader(sheet: ExcelJS.Worksheet): void {
  const header = sheet.getRow(1);
  header.font = { bold: true, size: 10 };
  header.eachCell((cell) => {
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: HEADER_FILL } };
    cell.border = { bottom: { style: "medium", color: { argb: "FF9CA3AF" } } };
    cell.alignment = { vertical: "middle" };
  });
  header.height = 18;
}

/**
 * The four distinct outcomes for one listed package.
 *
 * "Other version" is the one that has to be its own verdict rather than folded
 * into "Not found": for an advisory audit, *we have this package but not the
 * version named* is a different and much more interesting answer than *we do not
 * have this package*.
 */
function verdictOf(row: BulkSearchResult["rollup"][number]): {
  label: string;
  fill: string;
  text: string;
} {
  if (row.found && row.currentApplications > 0) {
    return { label: "In use", fill: "FFECFDF5", text: "FF047857" };
  }
  if (row.found) {
    return { label: "Removed", fill: "FFFFFBEB", text: "FFB45309" };
  }
  if (row.nameFound) {
    return { label: "Other version", fill: "FFEFF6FF", text: "FF1D4ED8" };
  }
  return { label: "Not found", fill: "FFF9FAFB", text: "FF6B7280" };
}

const SCOPE_LABELS: Record<BulkSearchResult["scope"], string> = {
  current: "Current builds only",
  historical: "Previously used, not now",
  all: "Current and historical",
};

const VERSION_KIND_LABELS: Record<string, string> = {
  any: "Any version",
  exact: "Exact version",
  "version-ignored": "Specifier ignored",
};
